---
abstract: 'Interact with the Apache BalancerManager'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-BalancerManager
requires:
  LWP::UserAgent: 6.04
  List::Util: 0
  Moo: 1.000007
  URI: 1.60
  Web::Scraper: 0.37
resources:
  repository: git://github.com/frioux/apache-balancermanager.git
version: 0.001001
